apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: sciath
data:
  ALLOWED_HOSTS: "api.sciath.io"
  FRONTEND_URL: "https://app.sciath.io"
  SCALEWAY_BUCKET_NAME: "sciath-reports"
