apiVersion: v1
kind: Namespace
metadata:
  name: sciath
  labels:
    app.kubernetes.io/part-of: sciath
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
